# fly.toml app configuration file generated for dziubenzo-mini-message-board on 2024-03-08T11:09:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dziubenzo-mini-message-board'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
